stages:
  - security

sast:
  stage: security
  script:
    - echo "Running SAST check"
    - semgrep --config=auto .
  allow_failure: true

secrets:
  stage: security
  script:
    - echo "Running secret detection"
    - gitleaks detect --source=. -v
  allow_failure: true

sca:
  stage: security
  script:
    - echo "Running SCA check"
    - trivy fs --scanners vuln --severity CRITICAL,HIGH .
  allow_failure: true
